[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$ManagerRoot,
    [Parameter(Mandatory=$true)][string]$OutputDirectory
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Write-Utf8NoBom{param([string]$Path,[string]$Text);$parent=Split-Path -Parent $Path;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[System.IO.File]::WriteAllText($Path,$Text,(New-Object System.Text.UTF8Encoding($false)))}
function Get-TextSha256{param([string]$Text);$bytes=[System.Text.Encoding]::UTF8.GetBytes($Text);$sha=[System.Security.Cryptography.SHA256]::Create();try{return([BitConverter]::ToString($sha.ComputeHash($bytes)).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function ConvertTo-StableJson{param($Value,[int]$Depth=20);return(($Value|ConvertTo-Json -Depth $Depth).Replace("`r`n","`n")+"`n")}
function Write-ValidatedMarkdown{param([string]$Path,$Lines,[int]$MinimumLineFeeds);$sb=New-Object System.Text.StringBuilder;$lineCount=0;foreach($line in @($Lines)){$s=[string]$line;if($s.Contains([string][char]10)-or$s.Contains([string][char]13)){throw('AI context Markdown line record contains embedded newline: '+$Path)};[void]$sb.Append($s);[void]$sb.Append([char]10);$lineCount++};if($lineCount-lt$MinimumLineFeeds){throw('AI context Markdown has too few explicit line records: '+$Path+'; line_count='+$lineCount)};$text=$sb.ToString();$lfCount=0;foreach($ch in $text.ToCharArray()){if([int]$ch-eq10){$lfCount++}};if($lfCount-ne$lineCount){throw('AI context Markdown line-feed invariant failed: '+$Path+'; lines='+$lineCount+' lf_count='+$lfCount)};if($text.Contains([string][char]13)){throw('AI context Markdown must use deterministic LF line endings: '+$Path)};Write-Utf8NoBom $Path $text;$roundTrip=[System.IO.File]::ReadAllText($Path,[System.Text.Encoding]::UTF8);if($roundTrip-cne$text){throw('AI context Markdown round-trip mismatch: '+$Path)}}
function Test-IsNestedFunctionAst{param($FunctionAst);$p=$FunctionAst.Parent;while($p){if($p -is [System.Management.Automation.Language.FunctionDefinitionAst]){return $true};$p=$p.Parent};return $false}
function Get-NestedFunctionNames{param($FunctionAst);$r=@();foreach($n in @($FunctionAst.FindAll({param($node)$node -is [System.Management.Automation.Language.FunctionDefinitionAst]},$true))){if($n-ne$FunctionAst){$r+=[string]$n.Name}};return @($r|Sort-Object -Unique)}
function Test-IsWindowsReservedSegment{param([string]$Segment);if(-not$Segment){return $false};$trimmed=([string]$Segment).TrimEnd([char[]]@(' ','.'));$dot=$trimmed.IndexOf('.');$stem=if($dot-ge0){$trimmed.Substring(0,$dot)}else{$trimmed};$stem=$stem.ToUpperInvariant().Replace([string][char]0x00B9,'1').Replace([string][char]0x00B2,'2').Replace([string][char]0x00B3,'3');if(@('CON','PRN','AUX','NUL','CLOCK$','CONIN$','CONOUT$')-contains$stem){return $true};return $stem-match'^COM[1-9]$'-or$stem-match'^LPT[1-9]$'}
function Test-SafeManagedRelativePath{param([string]$RelativePath);if([System.IO.Path]::IsPathRooted($RelativePath)){return $false};$rel=$RelativePath.Replace('\','/').Trim('/');if(-not$rel-or$rel.Contains(':')-or$rel.Length-gt512){return $false};foreach($seg in @($rel-split'/')){if(-not$seg-or$seg-eq'.'-or$seg-eq'..'-or$seg.Length-gt180-or$seg.EndsWith(' ')-or$seg.EndsWith('.')-or$seg-match'[<>"|?*\x00-\x1F]'-or(Test-IsWindowsReservedSegment $seg)){return $false}};return $true}

$root=(Resolve-Path -LiteralPath $ManagerRoot).Path.TrimEnd('\');$scriptPath=Join-Path $root 'Keelaryn__Manager.ps1';$versionPath=Join-Path $root '_manager_version.txt';$installPath=Join-Path $root '_manager_manifest.json';$policyPath=Join-Path $root 'product\manager_release.json';$releasePath=Join-Path $root 'product\release.json';$readmePath=Join-Path $root 'README_FIRST.md'
foreach($q in @($scriptPath,$versionPath,$installPath,$policyPath,$releasePath,$readmePath)){if(-not(Test-Path -LiteralPath $q -PathType Leaf)){throw('AI context preflight missing source: '+$q)}}
$version=(Get-Content -LiteralPath $versionPath -Raw -Encoding UTF8).Trim();$runtimeHash=(Get-FileHash -LiteralPath $scriptPath -Algorithm SHA256).Hash.ToLowerInvariant();$source=[System.IO.File]::ReadAllText($scriptPath,[System.Text.Encoding]::UTF8);$tokens=$null;$errors=$null;$ast=[System.Management.Automation.Language.Parser]::ParseInput($source,[ref]$tokens,[ref]$errors);if(@($errors).Count){throw(($errors|ForEach-Object{$_.Message})-join'; ')}
$im=(Get-Content -LiteralPath $installPath -Raw -Encoding UTF8)|ConvertFrom-Json;$policy=(Get-Content -LiteralPath $policyPath -Raw -Encoding UTF8)|ConvertFrom-Json;$release=(Get-Content -LiteralPath $releasePath -Raw -Encoding UTF8)|ConvertFrom-Json;$readme=[System.IO.File]::ReadAllText($readmePath,[System.Text.Encoding]::UTF8);$sm=[regex]::Match($source,'(?m)^\$ManagerVersion\s*=\s*"([^"]+)"\s*$');$rm=[regex]::Match($readme,'(?m)^# Keelaryn Manager\s+([^\s]+)\s*$')
if(-not$sm.Success-or-not$rm.Success-or$sm.Groups[1].Value-ne$version-or$rm.Groups[1].Value-ne$version){throw 'AI context preflight found inconsistent runtime/README version markers.'};if([string]$im.schema-ne'keelaryn.manager.installation.v1'-or[string]$im.manager_version-ne$version){throw 'AI context preflight found inconsistent installation manifest.'};if([string]$policy.schema-ne'keelaryn.manager.release-policy.v1'-or[string]$policy.manager_version-ne$version-or[string]$policy.native_update_schema-ne'keelaryn.manager.update.v2'){throw 'AI context preflight found inconsistent Manager release policy.'};try{if([version]([string]$policy.update_min_version)-gt[version]$version){throw 'impossible'}}catch{throw 'AI context preflight found invalid update floor.'};if([string]$release.schema-ne'keelaryn.system-release.v1'){throw 'AI context preflight found inconsistent system release.'}
$managed=@($im.managed_files|ForEach-Object{([string]$_).Replace('\','/')});$seen=@{};$prefix=[System.IO.Path]::GetFullPath($root).TrimEnd('\')+'\';foreach($rel in $managed){if(-not(Test-SafeManagedRelativePath $rel)){throw('Unsafe managed path: '+$rel)};$key=$rel.Normalize([System.Text.NormalizationForm]::FormC).ToLowerInvariant();if($seen.ContainsKey($key)){throw('Duplicate/Unicode-colliding managed path: '+$rel)};$seen[$key]=$true;$full=[System.IO.Path]::GetFullPath((Join-Path $root $rel.Replace('/','\')));if(-not$full.StartsWith($prefix,[System.StringComparison]::OrdinalIgnoreCase)-or-not(Test-Path -LiteralPath $full -PathType Leaf)){throw('Managed source unavailable: '+$rel)};$item=Get-Item -LiteralPath $full -Force;if(($item.Attributes-band[System.IO.FileAttributes]::ReparsePoint)-ne0-or$item.Length-gt64MB){throw('Unsafe managed source: '+$rel)}}
$badKeywordAdjacencyPattern='\b(?:return|throw|exit|break|continue)[$@\[]';$badBooleanGluePattern='\)-and-not\(';foreach($rel in $managed){if([System.IO.Path]::GetExtension($rel)-ieq'.ps1'){$managedPsText=[System.IO.File]::ReadAllText((Join-Path $root $rel.Replace('/','\')),[System.Text.Encoding]::UTF8);if($managedPsText-match'[^\x00-\x7F]'){throw('Windows PowerShell 5.1-compatible managed .ps1 source must be ASCII-only: '+$rel)};if($managedPsText-match$badKeywordAdjacencyPattern-or$managedPsText-match$badBooleanGluePattern){throw('Unsafe PowerShell lexical adjacency in managed source: '+$rel)}}}
if(Test-Path -LiteralPath $OutputDirectory){Remove-Item -LiteralPath $OutputDirectory -Recurse -Force};New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null;$functionsDir=Join-Path $OutputDirectory 'functions';$runtimeDir=Join-Path $OutputDirectory 'runtime';$routesDir=Join-Path $OutputDirectory 'routes';$managedDir=Join-Path $OutputDirectory 'managed';New-Item -ItemType Directory -Force -Path $functionsDir,$runtimeDir,$routesDir,$managedDir|Out-Null
foreach($rel in @($managed|Sort-Object)){if($rel-eq'Keelaryn__Manager.ps1'){continue};$src=Join-Path $root $rel.Replace('/','\');$dst=Join-Path $managedDir $rel.Replace('/','\');$parent=Split-Path -Parent $dst;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};Copy-Item -LiteralPath $src -Destination $dst -Force}
# Runtime slice invariant: AST and slicing use the same explicitly decoded UTF-8 string; each slice must exactly equal Extent.Text.
$all=@($ast.FindAll({param($node)$node -is [System.Management.Automation.Language.FunctionDefinitionAst]},$true));$top=@($all|Where-Object{-not(Test-IsNestedFunctionAst $_)}|Sort-Object{$_.Extent.StartOffset});if(-not$top){throw 'No top-level functions.'};$nameSet=@{};foreach($f in $top){$nameSet[[string]$f.Name]=$true};$raw=@{}
foreach($f in $top){$name=[string]$f.Name;$startOffset=[int]$f.Extent.StartOffset;$endOffset=[int]$f.Extent.EndOffset;if($startOffset-lt0-or$endOffset-lt$startOffset-or$endOffset-gt$source.Length){throw('Invalid AST extent for function: '+$name)};$text=$source.Substring($startOffset,$endOffset-$startOffset);if($text-cne[string]$f.Extent.Text){throw('AI context AST extent/text mismatch for function: '+$name)};$calls=@();foreach($cmd in @($f.FindAll({param($node)$node -is [System.Management.Automation.Language.CommandAst]},$true))){$called=$cmd.GetCommandName();if($called-and$called-ne$name-and$nameSet.ContainsKey([string]$called)){$calls+=[string]$called}};$calls=@($calls|Sort-Object -Unique);$slice='functions/'+$name+'.ps1';Write-Utf8NoBom (Join-Path $OutputDirectory $slice.Replace('/','\')) $text;$raw[$name]=[ordered]@{name=$name;start_line=[int]$f.Extent.StartLineNumber;end_line=[int]$f.Extent.EndLineNumber;line_count=[int]$f.Extent.EndLineNumber-[int]$f.Extent.StartLineNumber+1;sha256=Get-TextSha256 $text;slice=$slice;calls=$calls;called_by=@();nested_functions=@(Get-NestedFunctionNames $f)}}
foreach($name in @($raw.Keys)){foreach($called in @($raw[$name].calls)){if($raw.ContainsKey($called)){$raw[$called].called_by+=$name}}};$rows=@();foreach($f in $top){$r=$raw[[string]$f.Name];$r.called_by=@($r.called_by|Sort-Object -Unique);$rows+=[pscustomobject]$r}
$first=$top[0];$last=$top[-1];$preamble=$source.Substring(0,[int]$first.Extent.StartOffset);$dispatch=$source.Substring([int]$last.Extent.EndOffset);Write-Utf8NoBom (Join-Path $runtimeDir 'PREAMBLE.ps1') $preamble;Write-Utf8NoBom (Join-Path $runtimeDir 'DISPATCH.ps1') $dispatch;$segments=New-Object System.Collections.ArrayList;[void]$segments.Add([ordered]@{kind='preamble';slice='runtime/PREAMBLE.ps1';sha256=Get-TextSha256 $preamble})
for($i=0;$i-lt$top.Count;$i++){$f=$top[$i];$name=[string]$f.Name;[void]$segments.Add([ordered]@{kind='function';name=$name;slice='functions/'+$name+'.ps1';sha256=[string]$raw[$name].sha256});if($i-lt$top.Count-1){$next=$top[$i+1];$start=[int]$f.Extent.EndOffset;$len=[int]$next.Extent.StartOffset-$start;if($len-gt0){$gap=$source.Substring($start,$len);$g=('runtime/GLOBAL_GAP_{0:D3}.ps1'-f($i+1));Write-Utf8NoBom (Join-Path $OutputDirectory $g.Replace('/','\')) $gap;[void]$segments.Add([ordered]@{kind='global_gap';slice=$g;sha256=Get-TextSha256 $gap})}}};[void]$segments.Add([ordered]@{kind='dispatch';slice='runtime/DISPATCH.ps1';sha256=Get-TextSha256 $dispatch});$sb=New-Object System.Text.StringBuilder;foreach($seg in @($segments)){[void]$sb.Append([System.IO.File]::ReadAllText((Join-Path $OutputDirectory ([string]$seg.slice).Replace('/','\')),[System.Text.Encoding]::UTF8))};$runtimeTextHash=Get-TextSha256 $source;$rebuiltRuntime=$sb.ToString();$rebuiltRuntimeHash=Get-TextSha256 $rebuiltRuntime;if($rebuiltRuntimeHash-ne$runtimeTextHash){throw('AI context runtime segmentation is not lossless. expected='+$runtimeTextHash+' actual='+$rebuiltRuntimeHash+' source_chars='+$source.Length+' rebuilt_chars='+$rebuiltRuntime.Length)}
$routes=[ordered]@{manager_update=@('Read-ManagerUpdatePackage','Find-ManagerUpdateDecision','Install-ManagerPackage','Restore-ManagerSnapshot','Invoke-Update');hub_update=@('Get-ValidHubPackages','Find-HubUpdateDecision','Install-HubPackage','Invoke-Update');candidate_transport=@('Invoke-BuildCandidateTransport','Invoke-RestoreCandidateTransport','New-CandidateTransportDocument','Read-CandidateTransportDocument','Restore-CandidateTransportDocument','New-CandidateTransportOperations','Apply-CandidateTransportOperations','Assert-CandidateTransportRelativePath','Assert-CandidateTransportInboxOutputPath','Read-HubZipEntryBytes','Expand-HubZipPortableToDirectory','Get-ValidatedHubTransportIdentity','Write-CandidateTransportJsonAtomic');package_security=@('Assert-KeelarynArchiveEntrySafety','Test-ZipEnvelope','Read-ManagerUpdatePackage','Get-HubZipEnvelope');hub_integrity=@('Test-CanonicalBaselineConsistent','Get-ZipHashPair','Get-VaultHashPairAt','New-PortableSourceManifest');release_build=@('Invoke-BuildRelease','Invoke-BuildDistribution','Write-DeterministicZip');doctor=@('Invoke-Doctor','Get-VaultManifestDiagnostic');genesis=@('Invoke-Genesis','New-GenesisItemPlan','Assert-GenesisPlanDoesNotCollideWithTemplates','Expand-GenesisTemplate');migrations=@('Resolve-MigrationChain','Invoke-OneRegisteredMigration','Invoke-CheckMigrations','Invoke-ApplyMigrations','Invoke-AdoptInstanceIdentity','Invoke-MigrateLegacyNamespace','Invoke-MigrateLayout','Invoke-FinalizeLayout');ai_context=@('Invoke-BuildAIContext','Invoke-BuildRelease');transaction_safety=@('Publish-CompletedFileAtomically','Assert-CurrentHubSnapshotUnchanged','Install-HubPackage','Restore-ManagerSnapshot','Install-ManagerPackage');lock_diagnostics=@('Test-IsTransientFileLockException','Initialize-RestartManagerInterop','Get-RestartManagerLockOwners','Format-FileLockOwnerDiagnostic','New-FileLockDiagnosticException','Wait-FileReadyForAtomicReplace','Write-ManagerLogLine','Publish-CompletedFileAtomically');performance_hashing=@('Get-TextHashHex','Get-StreamHashHex','Get-BytesHashHex','Get-SafeTreeFileInventory','Get-PortableVaultFileInventory','Get-ZipHashPair','Get-VaultHashPairAt','Add-HubContentHashes','Invoke-Doctor');path_safety=@('Test-IsWindowsReservedPathSegment','Get-SafeTreeFileInventory','Test-ManagerManagedPath','Test-ZipEnvelope');tests_workspace=@('Initialize-TestsWorkspaceAt','Invoke-PrepareTests','Test-TestsWorkspaceSelfTest')}
$routeFiles=[ordered]@{manager_update=@('_manager_manifest.json','product/manager_release.json','product/docs/OPERATIONS.md');hub_update=@('product/docs/OPERATIONS.md','product/governance/hub/_System/PROTOCOL.md');candidate_transport=@('BUILD_CANDIDATE_TRANSPORT.cmd','RESTORE_CANDIDATE_TRANSPORT.cmd','product/docs/CANDIDATE_TRANSPORT.md','product/docs/PRIVACY_AND_RELEASE.md','product/docs/ARCHITECTURE.md','product/docs/OPERATIONS.md','product/docs/AI_DEVELOPMENT.md');package_security=@('product/docs/PRIVACY_AND_RELEASE.md');hub_integrity=@('product/governance/hub/_System/PROTOCOL.md');release_build=@('_manager_manifest.json','product/manager_release.json','product/release.json','product/docs/RELEASE_BUILD.md');doctor=@('product/docs/OPERATIONS.md');genesis=@('product/docs/GENESIS_AND_ONBOARDING.md','product/docs/ARCHITECTURE.md','product/release.json','product/starter/hub/_System/GENESIS.md','product/governance/hub/_System/BOOTSTRAP.md');migrations=@('product/docs/MIGRATIONS.md','product/docs/LAYOUT.md','product/migrations/index.json','product/migrations/README.md');ai_context=@('BUILD_AI_CONTEXT.cmd','product/docs/AI_DEVELOPMENT.md','product/tools/New-KeelarynAIContext.ps1');transaction_safety=@('product/docs/ARCHITECTURE.md','product/docs/OPERATIONS.md');lock_diagnostics=@('product/docs/ARCHITECTURE.md','product/docs/OPERATIONS.md','product/docs/AI_DEVELOPMENT.md');performance_hashing=@('product/docs/ARCHITECTURE.md','product/tools/New-KeelarynAIContext.ps1');path_safety=@('product/docs/PRIVACY_AND_RELEASE.md');tests_workspace=@('PREPARE_TESTS.cmd','product/docs/TESTING.md','product/docs/LAYOUT.md','product/docs/AI_DEVELOPMENT.md')}
$routeRows=[ordered]@{};foreach($route in $routes.Keys){
    $entries=@($routes[$route]|Where-Object{$raw.ContainsKey([string]$_)})
    $recommended=New-Object System.Collections.ArrayList
    foreach($e in $entries){if(-not$recommended.Contains($e)){[void]$recommended.Add($e)};foreach($d in @($raw[$e].calls)){if(-not$recommended.Contains($d)){[void]$recommended.Add($d)}}}
    $recommended=@($recommended|Sort-Object)
    $related=@($routeFiles[$route]|Where-Object{$seen.ContainsKey(([string]$_).Normalize([System.Text.NormalizationForm]::FormC).ToLowerInvariant())})
    $runtimeBytes=0;foreach($fn in $recommended){$runtimeBytes += [long](Get-Item -LiteralPath (Join-Path $functionsDir ($fn+'.ps1'))).Length}
    $routeRows[$route]=[ordered]@{entry_functions=$entries;recommended_functions=$recommended;related_managed_files=$related;recommended_runtime_bytes=$runtimeBytes}
    $bundle=New-Object System.Collections.ArrayList
    [void]$bundle.Add('# Keelaryn Manager '+$version+' - route: '+$route)
    [void]$bundle.Add('')
    [void]$bundle.Add('Runtime SHA-256: `'+$runtimeHash+'`.')
    [void]$bundle.Add('')
    [void]$bundle.Add('This route is an index, not a duplicate code bundle. Load only the referenced exact slices/files.')
    [void]$bundle.Add('')
    [void]$bundle.Add('Entry function slices:')
    foreach($e in $entries){[void]$bundle.Add('- `functions/'+$e+'.ps1`')}
    [void]$bundle.Add('')
    [void]$bundle.Add('Recommended function slices:')
    foreach($fn in $recommended){[void]$bundle.Add('- `functions/'+$fn+'.ps1`')}
    [void]$bundle.Add('')
    [void]$bundle.Add('Related managed files:')
    foreach($rel in $related){[void]$bundle.Add('- `managed/'+$rel+'`')}
    [void]$bundle.Add('')
    [void]$bundle.Add('Approximate recommended runtime bytes: '+$runtimeBytes+'.')
    Write-ValidatedMarkdown (Join-Path $routesDir ($route+'.md')) $bundle 10
}
$paramRows=@();if($ast.ParamBlock){foreach($q in @($ast.ParamBlock.Parameters)){$paramRows += [ordered]@{name=[string]$q.Name.VariablePath.UserPath;text=[string]$q.Extent.Text}}};$fm=[ordered]@{schema='keelaryn.ai-context.function-map.v4';manager_version=$version;runtime_sha256=$runtimeHash;function_count=$rows.Count;functions=$rows};$rs=[ordered]@{schema='keelaryn.ai-context.runtime-surface.v1';manager_version=$version;runtime_sha256=$runtimeHash;runtime_text_sha256=$runtimeTextHash;parameters=$paramRows;segments=@($segments)};$tr=[ordered]@{schema='keelaryn.ai-context.task-router.v4';manager_version=$version;runtime_sha256=$runtimeHash;routes=$routeRows};$managedRows=@();foreach($rel in @($managed|Sort-Object)){$f=Get-Item -LiteralPath (Join-Path $root $rel.Replace('/','\'));$managedRows += [ordered]@{path=$rel;size_bytes=[long]$f.Length;sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant();context_path=$(if($rel-eq'Keelaryn__Manager.ps1'){'runtime segments + functions/'}else{'managed/'+$rel})}};$mm=[ordered]@{schema='keelaryn.ai-context.managed-file-map.v2';manager_version=$version;runtime_sha256=$runtimeHash;file_count=$managedRows.Count;files=$managedRows};Write-Utf8NoBom (Join-Path $OutputDirectory 'FUNCTION_MAP.json') (ConvertTo-StableJson $fm);Write-Utf8NoBom (Join-Path $OutputDirectory 'RUNTIME_SURFACE.json') (ConvertTo-StableJson $rs);Write-Utf8NoBom (Join-Path $OutputDirectory 'TASK_ROUTER.json') (ConvertTo-StableJson $tr);Write-Utf8NoBom (Join-Path $OutputDirectory 'MANAGED_FILE_MAP.json') (ConvertTo-StableJson $mm)
$start=New-Object System.Collections.ArrayList
[void]$start.Add('# Keelaryn Manager '+$version+' - compact development context')
[void]$start.Add('')
[void]$start.Add('Canonical runtime SHA-256: `'+$runtimeHash+'`.')
[void]$start.Add('')
[void]$start.Add('Start with `TASK_ROUTER.json`; route Markdown files are compact indexes only, then load exact function slices and files under `managed/`. Runtime segments reconstruct the canonical runtime text losslessly.')
[void]$start.Add('')
[void]$start.Add('Key invariants:')
[void]$start.Add('- Canonical filesystem/repository layout is `keelaryn/manager`, `keelaryn/hub`, `keelaryn/tests`; `Keelaryn__*` remains compatibility/wire naming where required.')
[void]$start.Add('- UPDATE payload, outer manifest and all active version surfaces must agree.')
[void]$start.Add('- Never extract/apply an unvalidated ZIP.')
[void]$start.Add('- Manager/Hub updates remain rollback-oriented and preserve local deployment state.')
[void]$start.Add('- Context reduction must never remove runtime capability or weaken validation.')
Write-ValidatedMarkdown (Join-Path $OutputDirectory 'START_HERE.md') $start 12
$manifestRows=@();foreach($f in @(Get-ChildItem -LiteralPath $OutputDirectory -File -Recurse -Force|Where-Object{$_.Name-ne'CONTEXT_MANIFEST.json'}|Sort-Object FullName)){$base=[System.IO.Path]::GetFullPath($OutputDirectory).TrimEnd('\')+'\';$rel=$f.FullName.Substring($base.Length).Replace('\','/');$manifestRows += [ordered]@{path=$rel;size_bytes=[long]$f.Length;sha256=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}};$cm=[ordered]@{schema='keelaryn.ai-context.manifest.v1';manager_version=$version;runtime_sha256=$runtimeHash;files=$manifestRows};Write-Utf8NoBom (Join-Path $OutputDirectory 'CONTEXT_MANIFEST.json') (ConvertTo-StableJson $cm);Write-Host('AI context generated: '+[System.IO.Path]::GetFullPath($OutputDirectory))-ForegroundColor Green
