[CmdletBinding()]
param([string]$RepositoryRoot=(Join-Path $PSScriptRoot '..'))
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
$RepositoryRoot=[IO.Path]::GetFullPath($RepositoryRoot).TrimEnd('\')
$runtimePath=Join-Path $RepositoryRoot 'manager\product\runtime\Keelaryn__Manager.ps1';$menuPath=Join-Path $RepositoryRoot 'manager\product\tools\KeelarynMenu.ps1';$docsPath=Join-Path $RepositoryRoot 'manager\product\docs\CANDIDATE_TRANSPORT.md'
function Assert([bool]$C,[string]$M){if(-not$C){throw $M}}
function F([string]$P,[string]$N){$t=$null;$e=$null;$a=[Management.Automation.Language.Parser]::ParseFile($P,[ref]$t,[ref]$e);if(@($e).Count){throw 'parse'};$all=@($a.FindAll({param($node)$node-is[Management.Automation.Language.FunctionDefinitionAst]},$true));$matches=New-Object System.Collections.ArrayList;foreach($row in $all){if([string]$row.Name-ceq[string]$N){[void]$matches.Add($row)}};$r=@($matches);if($r.Count-ne1){throw('function '+$N+' count='+$r.Count)};return [string]$r[0].Extent.Text}
$p=Join-Path $PSHOME 'powershell.exe';foreach($n in @('Invoke-Manager4174ReviewRegression.ps1','Invoke-Manager4174BootstrapRegression.ps1')){& $p -NoProfile -NonInteractive -ExecutionPolicy Bypass -File (Join-Path $RepositoryRoot ('tools\'+$n)) -RepositoryRoot $RepositoryRoot;if($LASTEXITCODE-ne0){throw($n+' failed')}}
Write-Host '  PASS inherited Manager 4.17.4 regressions'
$rt=[IO.File]::ReadAllText($runtimePath,[Text.Encoding]::UTF8);$mt=[IO.File]::ReadAllText($menuPath,[Text.Encoding]::UTF8);$dt=[IO.File]::ReadAllText($docsPath,[Text.Encoding]::UTF8)
Assert $rt.Contains('[string]$ExpectedInstanceId') 'missing ExpectedInstanceId';Assert $mt.Contains("@('-ExpectedInstanceId',`$hubExpectedInstanceId)") 'frontend expected instance missing';Assert $mt.Contains("'OpenHubInbox'") 'OpenHubInbox missing';Assert $dt.Contains('state/instances/<instance_id>/inbox') 'instance inbox docs missing';Assert $dt.Contains('Development > Open active Hub inbox') 'inbox UI docs missing'
Invoke-Expression (F $runtimePath 'Resolve-RegisteredInstanceContextEarly');$ExpectedInstanceId='11111111-1111-1111-1111-111111111111';function Read-InstanceRegistryEarly{return [pscustomobject]@{instances=@()}};function Read-ActiveInstanceEarly{return [pscustomobject]@{instance_id='22222222-2222-2222-2222-222222222222'}};$blocked=$false;try{$null=Resolve-RegisteredInstanceContextEarly}catch{$blocked=$_.Exception.Message.Contains('Expected=11111111-1111-1111-1111-111111111111')};Assert $blocked 'expected-instance guard did not fail closed'
Write-Host '  PASS expected-instance runtime guard'
Invoke-Expression (F $runtimePath 'Assert-NewRegisteredHubTargetPathSafe');$temp=Join-Path ([IO.Path]::GetTempPath()) ('k4175_'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($temp);try{$script:InstanceRegistryFile=Join-Path $temp 'instances.json';[IO.File]::WriteAllText($script:InstanceRegistryFile,'{}');$LayoutRoot=$temp.ToUpperInvariant();$Root=Join-Path $temp 'manager';$CanonicalTestsPath=Join-Path $temp 'tests';function Test-IsWindowsReservedPathSegment{return $false};function Test-KeelarynPathOverlap{return $false};function Get-ManagerInstanceRegistry{return [pscustomobject]@{instances=@()}};$target=Join-Path (Join-Path $temp.ToLowerInvariant() 'hubs') 'new-hub';$actual=Assert-NewRegisteredHubTargetPathSafe $target;Assert ([IO.Path]::GetFullPath($actual).Equals([IO.Path]::GetFullPath($target),[StringComparison]::OrdinalIgnoreCase)) 'case-insensitive Genesis path failed'}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force}}
Write-Host '  PASS Windows case-insensitive Genesis path'
Invoke-Expression (F $menuPath 'Import-Package');$temp=Join-Path ([IO.Path]::GetTempPath()) ('k4175imp_'+[guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($temp);try{$Inbox=Join-Path $temp 'mi';[void][IO.Directory]::CreateDirectory($Inbox);$activeInbox=Join-Path $temp 'hi';[void][IO.Directory]::CreateDirectory($activeInbox);$pkg=Join-Path $temp 'Keelaryn__Hub_APPROVED_test.zip';[IO.File]::WriteAllText($pkg,'approved');$script:Args=@();function Test-ReparsePoint{return $false};function Get-FrontendInstanceContext{return [pscustomobject]@{RegistryActive=$true;InstanceId='33333333-3333-3333-3333-333333333333';HubInbox=$activeInbox}};function Ensure-DirectorySafe([string]$Path,[string]$Purpose){if(-not(Test-Path $Path)){[void][IO.Directory]::CreateDirectory($Path)}};function Get-FileSha256Hex([string]$Path){return (Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant()};function Write-UiHost{};function Invoke-Manager([string[]]$ManagerArgs){$script:Args=@($ManagerArgs);return 0};function Request-CommitConfirmation{return $false};function Set-ActionSemantic{};$Replace=$false;$rc=Import-Package $pkg;Assert ($rc-eq0) 'Hub import failed';Assert ($script:Args.Count-eq3) 'Hub import args count';Assert ($script:Args[0]-ceq'-UpdateHub') 'Hub action';Assert ($script:Args[1]-ceq'-ExpectedInstanceId') 'expected flag';Assert ($script:Args[2]-ceq'33333333-3333-3333-3333-333333333333') 'expected id';Assert (Test-Path (Join-Path $activeInbox 'Keelaryn__Hub_APPROVED_test.zip')) 'copy not in active inbox'}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force}}
Write-Host '  PASS Hub import/update captured-instance binding'
Write-Host 'MANAGER 4.17.5 REVIEW REGRESSION: PASS' -ForegroundColor Green